version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      lexical:
        patterns:
          - '@lexical/*'
          - 'lexical'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      tanstack:
        patterns:
          - '@tanstack/*'
      drizzle:
        patterns:
          - 'drizzle-*'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'chore'
      include: 'scope'
