allowBuilds:
  esbuild: false
  lefthook: true
  sharp: false
  workerd: false

minimumReleaseAgeExclude:
  - '@better-auth/core@1.7.3'
  - '@better-auth/drizzle-adapter@1.7.3'
  - '@better-auth/kysely-adapter@1.7.3'
  - '@better-auth/memory-adapter@1.7.3'
  - '@better-auth/mongo-adapter@1.7.3'
  - '@better-auth/prisma-adapter@1.7.3'
  - '@better-auth/telemetry@1.7.3'
  - better-auth@1.7.3

overrides:
  vite: 'npm:@voidzero-dev/vite-plus-core@latest'

publicHoistPattern:
  - 'oxlint'
  - '@oxlint/plugins'
