INSERT INTO
    ingredients (name)
VALUES
    ('Ail en poudre'),
    ('Asperges'),
    ('Aubergine'),
    ('Avocat'),
    ('Basilic'),
    ('Beurre'),
    ('Boeuf'),
    ('Bouillon de bœuf'),
    ('Bouillon de légume'),
    ('Bouillon de poule'),
    ('Bouquet garni'),
    ('Butternut'),
    ('Carotte'),
    ('Champignon'),
    ('Chocolat'),
    ('Choux'),
    ('Citron vert'),
    ('Citrons'),
    ('Concombre'),
    ('Concassé de tomate'),
    ('Conserve Thon'),
    ('Coriandre an poudre'),
    ('Coriandre séchée'),
    ('Courgette'),
    ('Crevette'),
    ('Cumin'),
    ('Curcuma'),
    ('Curry japonais'),
    ('Curry rouge'),
    ('Câpres'),
    ('Haricots rouges'),
    ('Huile de tournesol'),
    ('Ketchup'),
    ('Lait'),
    ('Lait de coco'),
    ('Lardons'),
    ('Laurier'),
    ('Massalé'),
    ('Maïzena'),
    ('Miel'),
    ('Moutarde'),
    ('Mélange 4 épices'),
    ('Oignon'),
    ('Oignon nouveau'),
    ('Oignon rouge'),
    ('Origan'),
    ('Pak-choï'),
    ('Paleron'),
    ('Paprika'),
    ('Parmesan'),
    ('Patate douce'),
    ('Persil'),
    ('Persil séché'),
    ('Piment de cayenne'),
    ('Pois chiches'),
    ('Poitrine fumée'),
    ('Poivron'),
    ('Pomme de terre'),
    ('Pâte de curry jaune'),
    ('Pâte de tamarin'),
    ('Rhum'),
    ('Sauce huitre'),
    ('Sauce poisson'),
    ('Sauce soja'),
    ('Sauce Worcestershire'),
    ('Shiitaké'),
    ('Sucre'),
    ('Sucre roux'),
    ('Thym'),
    ('Tomate'),
    ('Tomates pelées'),
    ('Viande hachée'),
    ('Vin blanc'),
    ('Vin rouge'),
    ('Vinaigre de riz'),
    ('Yaourt'),
    ('Échalote'),
    ('Échine de porc'),
    ('Épinard'),
    ('Escalope de dinde'),
    ('Estragon'),
    ('Farine'),
    ('Filet de poulet'),
    ('Filet mignon'),
    ('Fromage râpé'),
    ('Galettes'),
    ('Garam massala'),
    ('Gingembre'),
    ('Gousse d''ail'),
    ('Œuf');