/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoppingListRouteImport } from './routes/shopping-list'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsUnitsRouteImport } from './routes/settings/units'
import { Route as SettingsIngredientsRouteImport } from './routes/settings/ingredients'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as RecipeNewRouteImport } from './routes/recipe/new'
import { Route as RecipeIdRouteImport } from './routes/recipe/$id'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as RecipeEditIdRouteImport } from './routes/recipe/edit.$id'
import { Route as ApiImageIdRouteImport } from './routes/api/image/$id'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'

const ShoppingListRoute = ShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUnitsRoute = SettingsUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIngredientsRoute = SettingsIngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const RecipeNewRoute = RecipeNewRouteImport.update({
  id: '/recipe/new',
  path: '/recipe/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeIdRoute = RecipeIdRouteImport.update({
  id: '/recipe/$id',
  path: '/recipe/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeEditIdRoute = RecipeEditIdRouteImport.update({
  id: '/recipe/edit/$id',
  path: '/recipe/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageIdRoute = ApiImageIdRouteImport.update({
  id: '/api/image/$id',
  path: '/api/image/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shopping-list': typeof ShoppingListRoute
  '/auth/login': typeof AuthLoginRoute
  '/recipe/$id': typeof RecipeIdRoute
  '/recipe/new': typeof RecipeNewRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/ingredients': typeof SettingsIngredientsRoute
  '/settings/units': typeof SettingsUnitsRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/image/$id': typeof ApiImageIdRoute
  '/recipe/edit/$id': typeof RecipeEditIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/shopping-list': typeof ShoppingListRoute
  '/auth/login': typeof AuthLoginRoute
  '/recipe/$id': typeof RecipeIdRoute
  '/recipe/new': typeof RecipeNewRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/ingredients': typeof SettingsIngredientsRoute
  '/settings/units': typeof SettingsUnitsRoute
  '/settings': typeof SettingsIndexRoute
  '/api/image/$id': typeof ApiImageIdRoute
  '/recipe/edit/$id': typeof RecipeEditIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shopping-list': typeof ShoppingListRoute
  '/auth/login': typeof AuthLoginRoute
  '/recipe/$id': typeof RecipeIdRoute
  '/recipe/new': typeof RecipeNewRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/ingredients': typeof SettingsIngredientsRoute
  '/settings/units': typeof SettingsUnitsRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/image/$id': typeof ApiImageIdRoute
  '/recipe/edit/$id': typeof RecipeEditIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/settings'
    | '/shopping-list'
    | '/auth/login'
    | '/recipe/$id'
    | '/recipe/new'
    | '/settings/account'
    | '/settings/ingredients'
    | '/settings/units'
    | '/settings/'
    | '/api/image/$id'
    | '/recipe/edit/$id'
    | '/api/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/shopping-list'
    | '/auth/login'
    | '/recipe/$id'
    | '/recipe/new'
    | '/settings/account'
    | '/settings/ingredients'
    | '/settings/units'
    | '/settings'
    | '/api/image/$id'
    | '/recipe/edit/$id'
    | '/api/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/settings'
    | '/shopping-list'
    | '/auth/login'
    | '/recipe/$id'
    | '/recipe/new'
    | '/settings/account'
    | '/settings/ingredients'
    | '/settings/units'
    | '/settings/'
    | '/api/image/$id'
    | '/recipe/edit/$id'
    | '/api/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ShoppingListRoute: typeof ShoppingListRoute
  AuthLoginRoute: typeof AuthLoginRoute
  RecipeIdRoute: typeof RecipeIdRoute
  RecipeNewRoute: typeof RecipeNewRoute
  ApiImageIdRoute: typeof ApiImageIdRoute
  RecipeEditIdRoute: typeof RecipeEditIdRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopping-list': {
      id: '/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof ShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/units': {
      id: '/settings/units'
      path: '/units'
      fullPath: '/settings/units'
      preLoaderRoute: typeof SettingsUnitsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/ingredients': {
      id: '/settings/ingredients'
      path: '/ingredients'
      fullPath: '/settings/ingredients'
      preLoaderRoute: typeof SettingsIngredientsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/recipe/new': {
      id: '/recipe/new'
      path: '/recipe/new'
      fullPath: '/recipe/new'
      preLoaderRoute: typeof RecipeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$id': {
      id: '/recipe/$id'
      path: '/recipe/$id'
      fullPath: '/recipe/$id'
      preLoaderRoute: typeof RecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/edit/$id': {
      id: '/recipe/edit/$id'
      path: '/recipe/edit/$id'
      fullPath: '/recipe/edit/$id'
      preLoaderRoute: typeof RecipeEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image/$id': {
      id: '/api/image/$id'
      path: '/api/image/$id'
      fullPath: '/api/image/$id'
      preLoaderRoute: typeof ApiImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsIngredientsRoute: typeof SettingsIngredientsRoute
  SettingsUnitsRoute: typeof SettingsUnitsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsIngredientsRoute: SettingsIngredientsRoute,
  SettingsUnitsRoute: SettingsUnitsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ShoppingListRoute: ShoppingListRoute,
  AuthLoginRoute: AuthLoginRoute,
  RecipeIdRoute: RecipeIdRoute,
  RecipeNewRoute: RecipeNewRoute,
  ApiImageIdRoute: ApiImageIdRoute,
  RecipeEditIdRoute: RecipeEditIdRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
