/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoppingListRouteImport } from './routes/shopping-list'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecipeRouteImport } from './routes/recipe'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipeNewRouteImport } from './routes/recipe/new'
import { Route as RecipeIdRouteImport } from './routes/recipe/$id'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as RecipeEditIdRouteImport } from './routes/recipe/edit.$id'
import { ServerRoute as ApiImageIdServerRouteImport } from './routes/api/image/$id'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const ShoppingListRoute = ShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeRoute = RecipeRouteImport.update({
  id: '/recipe',
  path: '/recipe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeNewRoute = RecipeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RecipeRoute,
} as any)
const RecipeIdRoute = RecipeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecipeRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeEditIdRoute = RecipeEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => RecipeRoute,
} as any)
const ApiImageIdServerRoute = ApiImageIdServerRouteImport.update({
  id: '/api/image/$id',
  path: '/api/image/$id',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipe': typeof RecipeRouteWithChildren
  '/settings': typeof SettingsRoute
  '/shopping-list': typeof ShoppingListRoute
  '/auth/login': typeof AuthLoginRoute
  '/recipe/$id': typeof RecipeIdRoute
  '/recipe/new': typeof RecipeNewRoute
  '/recipe/edit/$id': typeof RecipeEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipe': typeof RecipeRouteWithChildren
  '/settings': typeof SettingsRoute
  '/shopping-list': typeof ShoppingListRoute
  '/auth/login': typeof AuthLoginRoute
  '/recipe/$id': typeof RecipeIdRoute
  '/recipe/new': typeof RecipeNewRoute
  '/recipe/edit/$id': typeof RecipeEditIdRoute
}
export interface FileRoutesById {
  '__root__': typeof rootRouteImport
  '/': typeof IndexRoute
  '/recipe': typeof RecipeRouteWithChildren
  '/settings': typeof SettingsRoute
  '/shopping-list': typeof ShoppingListRoute
  '/auth/login': typeof AuthLoginRoute
  '/recipe/$id': typeof RecipeIdRoute
  '/recipe/new': typeof RecipeNewRoute
  '/recipe/edit/$id': typeof RecipeEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recipe'
    | '/settings'
    | '/shopping-list'
    | '/auth/login'
    | '/recipe/$id'
    | '/recipe/new'
    | '/recipe/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recipe'
    | '/settings'
    | '/shopping-list'
    | '/auth/login'
    | '/recipe/$id'
    | '/recipe/new'
    | '/recipe/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/recipe'
    | '/settings'
    | '/shopping-list'
    | '/auth/login'
    | '/recipe/$id'
    | '/recipe/new'
    | '/recipe/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipeRoute: typeof RecipeRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ShoppingListRoute: typeof ShoppingListRoute
  AuthLoginRoute: typeof AuthLoginRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/image/$id': typeof ApiImageIdServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/image/$id': typeof ApiImageIdServerRoute
}
export interface FileServerRoutesById {
  '__root__': typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/image/$id': typeof ApiImageIdServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$' | '/api/image/$id'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$' | '/api/image/$id'
  id: '__root__' | '/api/auth/$' | '/api/image/$id'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiImageIdServerRoute: typeof ApiImageIdServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopping-list': {
      id: '/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof ShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe': {
      id: '/recipe'
      path: '/recipe'
      fullPath: '/recipe'
      preLoaderRoute: typeof RecipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/new': {
      id: '/recipe/new'
      path: '/new'
      fullPath: '/recipe/new'
      preLoaderRoute: typeof RecipeNewRouteImport
      parentRoute: typeof RecipeRoute
    }
    '/recipe/$id': {
      id: '/recipe/$id'
      path: '/$id'
      fullPath: '/recipe/$id'
      preLoaderRoute: typeof RecipeIdRouteImport
      parentRoute: typeof RecipeRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/edit/$id': {
      id: '/recipe/edit/$id'
      path: '/edit/$id'
      fullPath: '/recipe/edit/$id'
      preLoaderRoute: typeof RecipeEditIdRouteImport
      parentRoute: typeof RecipeRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/image/$id': {
      id: '/api/image/$id'
      path: '/api/image/$id'
      fullPath: '/api/image/$id'
      preLoaderRoute: typeof ApiImageIdServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface RecipeRouteChildren {
  RecipeIdRoute: typeof RecipeIdRoute
  RecipeNewRoute: typeof RecipeNewRoute
  RecipeEditIdRoute: typeof RecipeEditIdRoute
}

const RecipeRouteChildren: RecipeRouteChildren = {
  RecipeIdRoute: RecipeIdRoute,
  RecipeNewRoute: RecipeNewRoute,
  RecipeEditIdRoute: RecipeEditIdRoute,
}

const RecipeRouteWithChildren = RecipeRoute._addFileChildren(RecipeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipeRoute: RecipeRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ShoppingListRoute: ShoppingListRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiImageIdServerRoute: ApiImageIdServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
