name: Quality Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: voidzero-dev/setup-vp@c9c4510a7d35d8bb0afdbe4092bae2676c893c8f # v1.16.0
        with:
          node-version: '24'
          cache: true

      - name: Install dependencies
        run: vp install --frozen-lockfile

      - name: Run linter
        run: vp check

  knip:
    name: Knip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: voidzero-dev/setup-vp@c9c4510a7d35d8bb0afdbe4092bae2676c893c8f # v1.16.0
        with:
          node-version: '24'
          cache: true

      - name: Install dependencies
        run: vp install --frozen-lockfile

      - name: Run knip
        run: vp run knip
